version: '3.8'

services:
  apigateway:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "80"
    networks:
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apigateway.rule=Host(`apigateway.localhost`)"


networks:
  traefik:
    external: true
    name: traefik_default