version: '3.8'

services:
  apigateway:
    container_name: apigateway-app
    hostname: apigateway
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - redis
    networks:
      api_gateway: {}

  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: apigateway-redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      api_gateway: {}

volumes:
  redis_data:
    driver: local

networks:
  api_gateway:
    external: false
    name: api_gateway